from typing import NoReturn

formats: dict[str, str]

class EOFCommentsError(Exception): ...

class Comments:
    formats: dict[str, str]
    langs: dict[str, tuple[int, bool]]
    def __init__(self, mappings: dict[str, tuple[int, bool]] = ...) -> None: ...
    def is_available(self, lang: str) -> bool: ...
    def fill_langs(self) -> NoReturn: ...
    def generate(self) -> dict[str, str]: ...

# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
