from .args.parsing import arg_parser_init as arg_parser_init, indent_handler as indent_handler
from .comments import Comments as Comments
from .file import bootstrap_paths as bootstrap_paths, modify_file as modify_file, open_batch_paths as open_batch_paths
from .util import die as die, gen_indent_maps as gen_indent_maps
from io import TextIOWrapper
from typing import NoReturn

def get_last_line(file: TextIOWrapper) -> tuple[str, bool]: ...
def eof_comment_search(files: dict[str, tuple[TextIOWrapper, str]], comments: Comments, newline: bool) -> dict[str, tuple[tuple[TextIOWrapper, bool], str, bool]]: ...
def append_eof_comment(files: dict[str, tuple[tuple[TextIOWrapper, bool], str, bool]], comments: Comments, newline: bool) -> NoReturn: ...
def main() -> int: ...

# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
