from typing import NoReturn

def error(*msg, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
def die(*msg, code: int = 0, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
def gen_indent_maps(maps: list[tuple[str, int, bool]]) -> dict[str, tuple[int] | tuple[int, bool]] | None: ...

# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
