from .types.typeddict import IndentHandler as IndentHandler, IndentMap as IndentMap
from typing import NoReturn

def error(*msg, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
def die(*msg, code: int = 0, end: str = '\n', sep: str = ' ', flush: bool = False) -> NoReturn: ...
def gen_indent_maps(maps: list[IndentHandler]) -> dict[str, IndentMap] | None: ...
# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
