from ..util import die as die
from argparse import ArgumentParser, Namespace
from typing import Any

def bootstrap_args(parser: ArgumentParser, specs: tuple[tuple[list[str], dict[str, Any]]]) -> Namespace: ...
def arg_parser_init() -> tuple[ArgumentParser, Namespace]: ...
def indent_handler(indent: str) -> list[tuple[str, int, bool]]: ...

# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
