from ..types.typeddict import IndentHandler as IndentHandler, ParserSpec as ParserSpec
from ..util import die as die
from argparse import ArgumentParser, Namespace

def bootstrap_args(parser: ArgumentParser, specs: tuple[ParserSpec]) -> Namespace: ...
def arg_parser_init() -> tuple[ArgumentParser, Namespace]: ...
def indent_handler(indent: str) -> list[IndentHandler]: ...
# vim:ts=4:sts=4:sw=4:et:ai:si:sta:
